-- CreateTable
CREATE TABLE "File" (
    "FileID" UUID NOT NULL,
    "FileName" VARCHAR(511) NOT NULL,
    "Path" VARCHAR(511) NOT NULL,
    "UserID" UUID NOT NULL,
    "CreatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UpdatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "File_pkey" PRIMARY KEY ("FileID")
);

-- AddForeignKey
ALTER TABLE "File" ADD CONSTRAINT "File_UserID_fkey" FOREIGN KEY ("UserID") REFERENCES "User"("UserID") ON DELETE RESTRICT ON UPDATE CASCADE;
